# Generated by Django 3.2.9 on 2021-11-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carne', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Encurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coladmin.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremateria', models.CharField(max_length=100)),
                ('alumno', models.ManyToManyField(through='coladmin.Encurso', to='coladmin.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='encurso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coladmin.materias'),
        ),
    ]
